const FETCH_BLOGS_START = 'FETCH_BLOGS_START'
const FETCH_BLOGS_SUCC = 'FETCH_BLOGS_SUCC'
const FETCH_BLOGS_FAILURE = 'FETCH_BLOGS_FAILURE'

export {
  FETCH_BLOGS_START,
  FETCH_BLOGS_SUCC,
  FETCH_BLOGS_FAILURE
}