const FETCH_CATEGORIES_START = 'FETCH_CATEGORIES_START'
const FETCH_CATEGORIES_SUCCESS = 'FETCH_CATEGORIES_SUCCESS'
const FETCH_CATEGORIES_FAIURE = 'FETCH_CATEGORIES_FAILURE'

export {
  FETCH_CATEGORIES_START,
  FETCH_CATEGORIES_SUCCESS,
  FETCH_CATEGORIES_FAIURE
}
